# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170612_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
