# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170617_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='lang',
            field=models.CharField(default='cpp', max_length=10),
        ),
    ]
