# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_coder_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='lang',
            field=models.CharField(default='cpp', max_length=10, validators=[users.models.validate_lang]),
        ),
    ]
