# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import submissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.CharField(default=b'cpp', max_length=10, validators=[submissions.models.validate_lang]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
