# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20170623_1051'),
        ('submissions', '0002_auto_20170619_0516'),
    ]

    operations = [
    ]
