# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import submissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_merge_20170623_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.CharField(default='cpp', max_length=10, validators=[submissions.models.validate_lang]),
        ),
    ]
