# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_auto_20170624_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inp', models.FileField(upload_to='test/')),
                ('out', models.FileField(upload_to='test/')),
            ],
        ),
    ]
