# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_auto_20170628_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='inp',
            field=models.FileField(null=True, upload_to='test/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='out',
            field=models.FileField(null=True, upload_to='test/'),
        ),
    ]
