# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_auto_20170630_1035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
