# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_submission_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='toe',
            field=models.CharField(default='1.00', max_length=10),
        ),
    ]
