# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('statement', models.CharField(max_length=500)),
                ('input', models.CharField(max_length=100)),
                ('output', models.CharField(max_length=100)),
                ('tl', models.FloatField(default=2.0)),
                ('ml', models.IntegerField()),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inp', models.FileField(null=True, upload_to='test/')),
                ('out', models.FileField(null=True, upload_to='test/')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problemset.Problem')),
            ],
        ),
    ]
