# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='favorite',
            new_name='todo',
        ),
    ]
