# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0002_auto_20170701_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='todo',
        ),
    ]
