# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 05:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problemset', '0003_remove_problem_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
