# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 07:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0004_problem_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
