# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0006_problem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
