# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0007_problem_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='checker',
            field=models.FileField(default='/home/nishant/Documents/django/OJ/media/default_tester.cpp', upload_to=''),
        ),
    ]
